# LobbyCore by David Flash Configuration File
# Version 1.0.6

# Custom Settings


# LOBBY 


# The world where the Lobby is (NOTICE! The world needs to be loaded!)
world: "Lobby"

# Message that will be sent to players chat
message: "§f[§gFlash§fCore] §aYou were teleported to §fLobby!"

# Messages that will appear on players screen
title: "§cTeleporting.."
subtitle: "§fTo Hub"

# What gamemode will be applied when you do /hub (NEEDS TO BE NUMERIC)
gamemode: 2


# INFOUI (Experimental)

# Do you want to enable this feature? (true / false)

enabled: false

# What message should appear in InfoUI (Use \n for line break)

text: "Put what text you want here \n in config.yml!"